# ======================================================================================================================
# Docker - Docker-Compose                                                   https://docs.docker.com/compose/compose-file
# ======================================================================================================================
# >>>> Environment
services:
  # --------------------------------------------------------------------------------------------------------------------
  # Database
  # --------------------------------------------------------------------------------------------------------------------
  mysql:
    container_name: ${PROJECT_NAME}_mysql_in_${DOCKER_ENVIRONMENT}
    build:
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    env_file:
      - database/mysql/.env
    networks:
      backend:
        ipv4_address: ${MYSQL_NETWORK_BACKEND_IP_ADDRESS}
    ports:
      - ${MYSQl_PORT}:3306
    expose:
      - 3306/tcp
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 7168M
        reservations:
          memory: 4096M

# ----------------------------------------------------------------------------------------------------------------------
# Volumes
# ----------------------------------------------------------------------------------------------------------------------
volumes:
  mysql_volume: { }