# ======================================================================================================================
# Symfony Local Web Server
# ======================================================================================================================
# >>>> Document - https://symfony.com/doc/current/setup/symfony_server.html#running-commands-with-different-php-versions

# ----------------------------------------------------------------------------------------------------------------------
# Proxy
# ----------------------------------------------------------------------------------------------------------------------
#proxy:
#  domains:
#    - domain1
#    - domain2

# ----------------------------------------------------------------------------------------------------------------------
# HTTP
# ----------------------------------------------------------------------------------------------------------------------
http:
  document_root: public/
  passthru: index.php
  port: 8000
  preferred_port: 8001
  p12: path/to/p12_cert
  allow_http: true
  no_tls: true
  daemon: true
  use_gzip: true

# ----------------------------------------------------------------------------------------------------------------------
# Workers
# ----------------------------------------------------------------------------------------------------------------------
workers:
  # built-in command that builds and watches front-end assets
  # npm_encore_watch:
  #     cmd: ['npx', 'encore', 'dev', '--watch']
  #npm_encore_watch: ~

  # built-in command that starts messenger consumer
  # messenger_consume_async:
  #     cmd: ['symfony', 'console', 'messenger:consume', 'async']
  #     watch: ['config', 'src', 'templates', 'vendor']
  messenger_consume_async: ~

  # you can also add your own custom commands
  #build_spa:
  #  cmd: ['npm', '--cwd', './spa/', 'dev']

  # auto start Docker compose when starting server (available since Symfony CLI 5.7.0)
  docker_compose: ~