# ======================================================================================================================
# Docker - Docker-Compose                                                   https://docs.docker.com/compose/compose-file
# ======================================================================================================================
# >>>> Default Environment                                     https://docs.docker.com/compose/compose-file/05-services/
services:
  # --------------------------------------------------------------------------------------------------------------------
  # App                                                                                     https://hub.docker.com/_/php
  # --------------------------------------------------------------------------------------------------------------------
  # >>>> PHP - Symfony Framework

  # --------------------------------------------------------------------------------------------------------------------
  # Cache                                                                                 https://hub.docker.com/_/redis
  # --------------------------------------------------------------------------------------------------------------------
  # >>>> Redis

  # --------------------------------------------------------------------------------------------------------------------
  # Database                                                                           https://hub.docker.com/_/postgres
  # --------------------------------------------------------------------------------------------------------------------
  postgres:
    env_file:
      - scripts/docker/containers/database/postgres/.env
    networks:
      - back-end
    expose:
      - 5432/tcp
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgres/data
        volume:
          nocopy: true
    restart: always
  # --------------------------------------------------------------------------------------------------------------------
  # Message                                                                            https://hub.docker.com/_/rabbitmq
  # --------------------------------------------------------------------------------------------------------------------
  # >>>> RabbitMQ

  # --------------------------------------------------------------------------------------------------------------------
  # Server                                                                                https://hub.docker.com/_/nginx
  # --------------------------------------------------------------------------------------------------------------------
  # >>>> Nginx

# ----------------------------------------------------------------------------------------------------------------------
# Networks                                                     https://docs.docker.com/compose/compose-file/06-networks/
# ----------------------------------------------------------------------------------------------------------------------
networks:
  front-end:
    driver: bridge
    enable_ipv6: false
  back-end:
    driver: bridge
    enable_ipv6: false

# ----------------------------------------------------------------------------------------------------------------------
# Volumes                                                       https://docs.docker.com/compose/compose-file/07-volumes/
# ----------------------------------------------------------------------------------------------------------------------
volumes:
  postgres_volume: { }

# ----------------------------------------------------------------------------------------------------------------------
# Configs                                                       https://docs.docker.com/compose/compose-file/08-configs/
# ----------------------------------------------------------------------------------------------------------------------
#configs:
#  http_config:
#    external: false

# ----------------------------------------------------------------------------------------------------------------------
# Secrets                                                       https://docs.docker.com/compose/compose-file/09-secrets/
# ----------------------------------------------------------------------------------------------------------------------
#secrets:
#  server-certificate:
#    file: ./server.cert