# ======================================================================================================================
# Docker - Docker-Compose                                                   https://docs.docker.com/compose/compose-file
# ======================================================================================================================
version: "3.9"
services:
  # --------------------------------------------------------------------------------------------------------------------
  # Database
  # --------------------------------------------------------------------------------------------------------------------
  mongo:
    build:
      context: .
      dockerfile: scripts/docker/containers/database/mongo/Dockerfile
    env_file:
      - scripts/docker/containers/database/mongo/.env
    networks:
      backend:
        aliases:
          - database
    ports:
      - "27017:27017"
    expose:
      - 27017/tcp
    volumes:
      - type: volume
        source: mongo_volume
        target: /data/db
        volume:
          nocopy: true
      - type: bind
        source: ./var/log/database/mongodb
        target: /var/log/mongodb
    restart: always

# ----------------------------------------------------------------------------------------------------------------------
# Networks
# ----------------------------------------------------------------------------------------------------------------------
networks:
  default:
    enable_ipv6: false
  front-end:
    enable_ipv6: false
  backend:
    enable_ipv6: false

# ----------------------------------------------------------------------------------------------------------------------
# Volumes
# ----------------------------------------------------------------------------------------------------------------------
volumes:
  mongo_volume: { }