# ======================================================================================================================
# Docker - Docker-Compose                                                   https://docs.docker.com/compose/compose-file
# ======================================================================================================================
# >>>> Environment
services:
  # --------------------------------------------------------------------------------------------------------------------
  # Database
  # --------------------------------------------------------------------------------------------------------------------
  mongo:
    container_name: ${DOCKER_CONTAINER_NAME}_mongo_in_${DOCKER_ENVIRONMENT}
    build:
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    env_file:
      - database/mongo/.env
    networks:
      backend:
        ipv4_address: ${MONGO_NETWORK_BACKEND_IP_ADDRESS}
    ports:
      - ${MONGO_NETWORK_PORT_DEFAULT}:27017
    expose:
      - 27017/tcp
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 7168M
        reservations:
          memory: 4096M

# ----------------------------------------------------------------------------------------------------------------------
# Volumes
# ----------------------------------------------------------------------------------------------------------------------
volumes:
  mongo_volume: { }