# ======================================================================================================================
# Supervisor                                                              https://symfony.com/doc/current/messenger.html
# ======================================================================================================================

[program:messenger-worker]
command=php /var/www/app/bin/console messenger:consume --all --limit=10 --memory-limit=128M --time-limit=3600
user=root
numprocs=2
startsecs=0
autostart=true
autorestart=true
startretries=5
process_name=%(program_name)s_%(process_num)02d
