# ======================================================================================================================
# Docker - Docker-Compose                                                   https://docs.docker.com/compose/compose-file
# ======================================================================================================================
# >>>> Dev Environment                                         https://docs.docker.com/compose/compose-file/05-services/
services:
  # --------------------------------------------------------------------------------------------------------------------
  # Cache                                                                                 https://hub.docker.com/_/redis
  # --------------------------------------------------------------------------------------------------------------------
  # >>>> Redis
  redis:
    container_name: ${DOCKER_PROJECT_NAME}-redis-${DOCKER_ENVIRONMENT}
    build:
      context: .
      dockerfile: scripts/containers/dev/cache/redis/Dockerfile
      args:
        - VERSION=${REDIS_VERSION:-7.0}
    env_file:
      - scripts/containers/dev/cache/redis/.env
    networks:
      back-end:
        ipv4_address: ${REDIS_NETWORK_BACKEND_IP_ADDRESS}
    expose:
      - 6379/tcp
    ports:
      - ${REDIS_NETWORK_PORT}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_volume:/data
    command: redis-server --save 60 1 --loglevel warning
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: 1024M
        reservations:
          memory: 512M
    restart: unless-stopped

  # --------------------------------------------------------------------------------------------------------------------
  # Database                                                                           https://hub.docker.com/_/postgres
  # --------------------------------------------------------------------------------------------------------------------
  # >>>> PostgreSQL
  postgres:
    container_name: ${DOCKER_PROJECT_NAME}-postgres-${DOCKER_ENVIRONMENT}
    build:
      context: .
      dockerfile: scripts/containers/dev/database/postgres/Dockerfile
      args:
        - VERSION=${POSTGRES_VERSION:-16}
      shm_size: 512mb
    env_file:
      - scripts/containers/dev/database/postgres/.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_USER=${POSTGRES_USER:-symfony}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
    networks:
      back-end:
        ipv4_address: ${POSTGRES_NETWORK_BACKEND_IP_ADDRESS}
    expose:
      - 5432/tcp
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-app}",
          "-U",
          "${POSTGRES_USER:-symfony}",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgres/data
        volume:
          nocopy: true
    labels:
      com.symfony.server.service-prefix: "DATABASE"
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: 2048M
        reservations:
          memory: 1024M
    restart: unless-stopped

  # --------------------------------------------------------------------------------------------------------------------
  # Message                                                                            https://hub.docker.com/_/rabbitmq
  # --------------------------------------------------------------------------------------------------------------------
  # >>>> RabbitMQ
  rabbitmq:
    container_name: ${DOCKER_PROJECT_NAME}-rabbitmq-${DOCKER_ENVIRONMENT}
    build:
      context: .
      dockerfile: scripts/containers/dev/message/rabbitmq/Dockerfile
      args:
        - VERSION=${RABBITMQ_VERSION:-3.13}
    env_file:
      - scripts/containers/dev/message/rabbitmq/.env
    networks:
      back-end:
        ipv4_address: ${RABBITMQ_NETWORK_BACKEND_IP_ADDRESS}
    expose:
      - 5672/tcp
      - 15672/tcp
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  # --------------------------------------------------------------------------------------------------------------------
  # Tools
  # --------------------------------------------------------------------------------------------------------------------
  # >>>> Kafka

  # --------------------------------------------------------------------------------------------------------------------
  # Utility
  # --------------------------------------------------------------------------------------------------------------------
  # >>>> PgAdmin
  pgadmin:
    #profiles: ["debug"]
    container_name: ${DOCKER_PROJECT_NAME}-pgadmin-${DOCKER_ENVIRONMENT}
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    networks:
      front-end:
        ipv4_address: ${PGADMIN_NETWORK_FRONTEND_IP_ADDRESS}
      back-end:
        ipv4_address: ${PGADMIN_NETWORK_BACKEND_IP_ADDRESS}
    expose:
      - 80/tcp
    ports:
      - ${PGADMIN_NETWORK_PORT}:80
    restart: unless-stopped

  # >>>> Mailer
  mailer:
    #profiles: ["debug"]
    container_name: ${DOCKER_PROJECT_NAME}-mailer-${DOCKER_ENVIRONMENT}
    image: schickling/mailcatcher
    networks:
      front-end:
        ipv4_address: ${MAILER_NETWORK_FRONTEND_IP_ADDRESS}
      back-end:
        ipv4_address: ${MAILER_NETWORK_BACKEND_IP_ADDRESS}
    expose:
      - 1080/tcp
      - 1025/tcp
    ports:
      - ${MAILER_NETWORK_HTTP_PORT}:1080
      - ${MAILER_NETWORK_SMTP_PORT}:1025
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: 256M
        reservations:
          memory: 128M
    restart: unless-stopped

# ----------------------------------------------------------------------------------------------------------------------
# Networks                                                     https://docs.docker.com/compose/compose-file/06-networks/
# ----------------------------------------------------------------------------------------------------------------------
networks:
  front-end:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK_FRONTEND_IPAM_CONFIG_SUBNET}
  back-end:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK_BACKEND_IPAM_CONFIG_SUBNET}

# ----------------------------------------------------------------------------------------------------------------------
# Volumes                                                       https://docs.docker.com/compose/compose-file/07-volumes/
# ----------------------------------------------------------------------------------------------------------------------
volumes:
  redis_volume: {}
  postgres_volume: {}

# ----------------------------------------------------------------------------------------------------------------------
# Configs                                                       https://docs.docker.com/compose/compose-file/08-configs/
# ----------------------------------------------------------------------------------------------------------------------
#configs:
#  http_config:
#    external: false

# ----------------------------------------------------------------------------------------------------------------------
# Secrets                                                       https://docs.docker.com/compose/compose-file/09-secrets/
# ----------------------------------------------------------------------------------------------------------------------
#secrets:
#  server-certificate:
#    file: ./server.cert

# ----------------------------------------------------------------------------------------------------------------------
# Logs
# ----------------------------------------------------------------------------------------------------------------------
#x-logging: &default-logging
#  driver: "json-file"
#  options:
#    max-size: "10m"
#    max-file: "3"
