# ======================================================================================================================
# Docker - Docker-Compose                                                   https://docs.docker.com/compose/compose-file
# ======================================================================================================================
version: "3.9"
services:
  # --------------------------------------------------------------------------------------------------------------------
  # Server
  # --------------------------------------------------------------------------------------------------------------------
  apache:
    build:
      context: .
      dockerfile: scripts/docker/containers/server/apache/Dockerfile
      shm_size: 2gb
    env_file:
      - scripts/docker/containers/server/apache/.env
    networks:
      front-end:
        aliases:
          - application
    expose:
      - 80/tcp
      - 443/tcp
    links:
      - php
    volumes:
      - type: bind
        source: ./app/public
        target: /usr/src/app/public
      - type: bind
        source: ./var/log/server/apache
        target: /var/log/apache
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 5m
      timeout: 3s
      retries: 3
      start_period: 1m
    restart: always

# ----------------------------------------------------------------------------------------------------------------------
# Networks
# ----------------------------------------------------------------------------------------------------------------------
networks:
  default:
    enable_ipv6: false
  front-end:
    enable_ipv6: false
  backend:
    enable_ipv6: false

# ----------------------------------------------------------------------------------------------------------------------
# Volumes
# ----------------------------------------------------------------------------------------------------------------------
volumes:
  mongo_volume: { }
  mysql_volume: { }